package pmx_test

import (
	"context"
	"testing"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/stretchr/testify/suite"
	"github.com/wcamarao/pmx"
	"github.com/wcamarao/pmx/test"
)

type InsertSuite struct {
	suite.Suite
	conn *pgx.Conn
}

func (s *InsertSuite) SetupTest() {
	s.conn = test.Connect()
}

func TestInsert(t *testing.T) {
	suite.Run(t, new(InsertSuite))
}

func (s *InsertSuite) TestStructPointer() {
	sample := test.Sample{
		ID:    "insert-pointer-id",
		Label: "insert-pointer-label",
	}

	tag, err := pmx.Insert(context.Background(), s.conn, &sample)
	s.EqualValues(1, tag.RowsAffected())
	s.Nil(err)

	var id, label string
	row := s.conn.QueryRow(context.Background(), "select * from samples where id = $1", "insert-pointer-id")
	err = row.Scan(&id, &label)
	s.Equal("insert-pointer-id", id)
	s.Equal("insert-pointer-label", label)
	s.Nil(err)
}

func (s *InsertSuite) TestAutoGenerated() {
	now := time.Now().Truncate(time.Millisecond)

	event := test.Event{
		RecordedAt: now,
	}

	tag, err := pmx.Insert(context.Background(), s.conn, &event)
	s.EqualValues(1, tag.RowsAffected())
	s.Nil(err)

	var position int
	var recordedAt time.Time
	row := s.conn.QueryRow(context.Background(), "select * from events where recorded_at = $1", now)
	err = row.Scan(&position, &recordedAt)
	s.Equal(now, recordedAt)
	s.NotZero(position)
	s.Nil(err)
}

func (s *InsertSuite) TestStructValue() {
	var sample test.Sample
	tag, err := pmx.Insert(context.Background(), s.conn, sample)
	s.Equal(pmx.ErrInvalidRef, err)
	s.Equal(pgconn.CommandTag{}, tag)
}

func (s *InsertSuite) TestMapPointer() {
	var sample map[string]string
	tag, err := pmx.Insert(context.Background(), s.conn, &sample)
	s.Equal(pmx.ErrInvalidRef, err)
	s.Equal(pgconn.CommandTag{}, tag)
}

func (s *InsertSuite) TestMapValue() {
	var sample map[string]string
	tag, err := pmx.Insert(context.Background(), s.conn, sample)
	s.Equal(pmx.ErrInvalidRef, err)
	s.Equal(pgconn.CommandTag{}, tag)
}
